[build]
  # Build command (not needed for static site)
  command = ""
  # Publish directory (all files in root)
  publish = "."
  # Functions directory (if we add serverless functions later)
  functions = "functions"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirects for SPA routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://api.openai.com https://api.elevenlabs.io https://translation.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.openai.com https://api.elevenlabs.io https://translation.googleapis.com wss://api.elevenlabs.io;"

# Environment variables will be set in Netlify dashboard
# Go to Site settings > Environment variables 